services:
  app:
    build: .
    ports:
      - "8000:8000"
    develop:
      watch:
        - action : sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: pyproject.toml
    depends_on:
      - db
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  db_test:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data
volumes:
  db_data:
  db_test_data:
